spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/carlofy_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pass123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
app.jwt.secret=${APP_JWT_SECRET:9a67471ec97aa3af1022e1f41723f5f2d68e4a7d1a2b3c4d5e6f7g8h9i0j1k2l}
app.jwt.expiration-ms=86400000

# Security
spring.main.allow-bean-definition-overriding=true
server.port=${PORT:8080}

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SPRING_MAIL_USERNAME:ritish1808@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:sradtvjxedpohwvs}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

# Payload Size Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=50MB
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
